name: earthcube-notebook
channels:
  - conda-forge
dependencies:
  - cartopy
  - cftime
  - fsspec=0.7.3
  - gcsfs
  - intake-esm
  - matplotlib
  - nc-time-axis
  - netcdf4
  - pangeo-notebook=2020.06.10
  - pip
  - watermark
  - zarr
