name: earthcube-notebook
channels:
  - conda-forge
dependencies:
  - cartopy
  - cftime
  - fsspec
  - gcsfs
  - intake-esm
  - nc-time-axis
  - netcdf4
  - pangeo-notebook=2020.05.04
  - pip
  - s3fs
  - watermark
  - zarr
